#!/bin/bash
size=$(ffprobe -v error -select_streams v:0 -show_entries stream=width,height -of json $1 | jq ".streams[0]")
width=$(echo "$size" | jq ".width")
height=$(echo "$size" | jq ".height")
echo "$width" "$height"
